// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The generator-changelog-html Authors

package plugin

import (
	"fmt"
	"html"
	"regexp"
	"strings"
	"time"
)

// aiTrailerPatterns matches known AI co-author trailers in commit messages.
var aiTrailerPatterns = []struct {
	pattern *regexp.Regexp
	label   string
}{
	{regexp.MustCompile(`(?i)co-authored-by:[^\n]*copilot`),        "GitHub Copilot"},
	{regexp.MustCompile(`(?i)co-authored-by:[^\n]*github-copilot`), "GitHub Copilot"},
	{regexp.MustCompile(`(?i)co-authored-by:[^\n]*claude`),         "Claude (Anthropic)"},
	{regexp.MustCompile(`(?i)co-authored-by:[^\n]*chatgpt`),        "ChatGPT (OpenAI)"},
	{regexp.MustCompile(`(?i)(?m)^ai-assisted:\s*true`),            "AI"},
	{regexp.MustCompile(`(?i)(?m)^generated-by:`),                  "AI"},
}

// detectAIAuthors returns deduplicated AI tool labels found in commit trailers.
func detectAIAuthors(commitMsg string) []string {
	seen := map[string]struct{}{}
	var labels []string
	for _, pat := range aiTrailerPatterns {
		if pat.pattern.MatchString(commitMsg) {
			if _, ok := seen[pat.label]; !ok {
				seen[pat.label] = struct{}{}
				labels = append(labels, pat.label)
			}
		}
	}
	return labels
}

const (
	breakingChangesSection = "Breaking Changes"
	featuresSection        = "Features"
	bugFixesSection        = "Bug Fixes"
	otherChangesSection    = "Other Changes"
)

type ReleaseContext struct {
	Version        string
	CurrentVersion string
	Branch         string
	Commits        []string
}

type GenerateOptions struct {
	Signature           bool
	AIDisclosure        bool
	AIDisclosureBadge   string
	AIDisclosureSection bool
}

type Generator struct {
	now func() time.Time
}

var conventionalHeaderPattern = regexp.MustCompile(`^(\w+)(\([\w-]+\))?(!)?:(.+)$`)

func New() *Generator {
	return &Generator{now: time.Now}
}

func DefaultGenerateOptions() GenerateOptions {
	return GenerateOptions{
		Signature:           false,
		AIDisclosure:        false,
		AIDisclosureBadge:   "🤖",
		AIDisclosureSection: false,
	}
}

func (g *Generator) Generate(ctx ReleaseContext, options ...GenerateOptions) string {
	generateOptions := DefaultGenerateOptions()
	if len(options) > 0 {
		generateOptions = options[0]
	}

	sections := map[string][]string{}
	type aiEntry struct {
		header string
		labels []string
	}
	var aiEntries []aiEntry

	for _, commit := range ctx.Commits {
		section, line := classifyCommit(commit)
		if section == "" || line == "" {
			continue
		}
		if generateOptions.AIDisclosure {
			if labels := detectAIAuthors(commit); len(labels) > 0 {
				badge := generateOptions.AIDisclosureBadge
				if badge == "" {
					badge = "🤖"
				}
				line = line + " " + badge
				if generateOptions.AIDisclosureSection {
					aiEntries = append(aiEntries, aiEntry{firstLine(commit), labels})
				}
			}
		}
		sections[section] = append(sections[section], line)
	}

	var builder strings.Builder
	builder.WriteString("<section class=\"changelog-entry\">\n")
	fmt.Fprintf(&builder, "  <h2>%s <small>%s</small></h2>\n", html.EscapeString(displayVersion(ctx.Version)), g.currentDate().Format("2006-01-02"))

	if meta := metadataLine(ctx); meta != "" {
		fmt.Fprintf(&builder, "  <p>%s</p>\n", html.EscapeString(meta))
	}

	for _, section := range []string{breakingChangesSection, featuresSection, bugFixesSection, otherChangesSection} {
		lines := sections[section]
		if len(lines) == 0 {
			continue
		}

		fmt.Fprintf(&builder, "  <h3>%s</h3>\n", html.EscapeString(section))
		builder.WriteString("  <ul>\n")
		for _, line := range lines {
			fmt.Fprintf(&builder, "    <li>%s</li>\n", html.EscapeString(line))
		}
		builder.WriteString("  </ul>\n")
	}

	if generateOptions.AIDisclosure && generateOptions.AIDisclosureSection && len(aiEntries) > 0 {
		builder.WriteString("  <details>\n    <summary>🤖 AI-Assisted Contributions</summary>\n")
		builder.WriteString("    <p>The following changes were co-authored with an AI assistant:</p>\n    <ul>\n")
		for _, e := range aiEntries {
			fmt.Fprintf(&builder, "      <li>%s &mdash; Co-authored with <strong>%s</strong></li>\n",
				html.EscapeString(e.header), html.EscapeString(strings.Join(e.labels, ", ")))
		}
		builder.WriteString("    </ul>\n    <p><em>Disclosed in accordance with project AI-usage policy (L-08 §8).</em></p>\n  </details>\n")
	}

	if generateOptions.Signature {
		builder.WriteString("  <footer><small>Generated by <a href=\"https://semrel.io\">semrel.io</a></small></footer>\n")
	}

	builder.WriteString("</section>")
	return builder.String()
}

func (g *Generator) currentDate() time.Time {
	if g != nil && g.now != nil {
		return g.now()
	}
	return time.Now()
}

func metadataLine(ctx ReleaseContext) string {
	parts := make([]string, 0, 2)
	if ctx.CurrentVersion != "" {
		parts = append(parts, "Previous release: "+displayVersion(ctx.CurrentVersion))
	}
	if strings.TrimSpace(ctx.Branch) != "" {
		parts = append(parts, "Branch: "+strings.TrimSpace(ctx.Branch))
	}
	return strings.Join(parts, " · ")
}

func classifyCommit(commit string) (string, string) {
	trimmed := strings.TrimSpace(commit)
	if trimmed == "" {
		return "", ""
	}

	if breaking, ok := breakingChangeText(trimmed); ok {
		return breakingChangesSection, breaking
	}

	header := firstLine(trimmed)
	matches := conventionalHeaderPattern.FindStringSubmatch(header)
	if len(matches) == 0 {
		return otherChangesSection, header
	}

	if matches[3] == "!" {
		return breakingChangesSection, header
	}

	switch strings.ToLower(matches[1]) {
	case "feat":
		return featuresSection, header
	case "fix", "perf", "revert":
		return bugFixesSection, header
	default:
		return otherChangesSection, header
	}
}

func breakingChangeText(message string) (string, bool) {
	for _, line := range strings.Split(message, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "BREAKING CHANGE:") {
			return trimmed, true
		}
	}
	return "", false
}

func firstLine(message string) string {
	message = strings.TrimSpace(message)
	if message == "" {
		return ""
	}
	parts := strings.SplitN(message, "\n", 2)
	return strings.TrimSpace(parts[0])
}

func displayVersion(version string) string {
	version = strings.TrimSpace(version)
	if version == "" {
		return "Unreleased"
	}
	if strings.HasPrefix(strings.ToLower(version), "v") {
		return version
	}
	return "v" + version
}
