// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The generator-changelog-html Authors

package plugin

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
)

func TestGeneratorGenerate(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	output := generator.Generate(ReleaseContext{
		Version:        "1.3.0",
		CurrentVersion: "1.2.0",
		Branch:         "main",
		Commits: []string{
			"feat: add <search>",
			"fix: escape & encode",
			"refactor!: remove deprecated endpoint",
		},
	})

	require.Equal(t, "<section class=\"changelog-entry\">\n  <h2>v1.3.0 <small>2026-05-25</small></h2>\n  <p>Previous release: v1.2.0 · Branch: main</p>\n  <h3>Breaking Changes</h3>\n  <ul>\n    <li>refactor!: remove deprecated endpoint</li>\n  </ul>\n  <h3>Features</h3>\n  <ul>\n    <li>feat: add &lt;search&gt;</li>\n  </ul>\n  <h3>Bug Fixes</h3>\n  <ul>\n    <li>fix: escape &amp; encode</li>\n  </ul>\n</section>", output)
}

func TestMetadataLine(t *testing.T) {
	t.Parallel()

	require.Equal(t, "", metadataLine(ReleaseContext{}))
	require.Equal(t, "Previous release: v1.2.0", metadataLine(ReleaseContext{CurrentVersion: "1.2.0"}))
	require.Equal(t, "Branch: main", metadataLine(ReleaseContext{Branch: "main"}))
}

func TestClassifyCommit(t *testing.T) {
	t.Parallel()

	section, line := classifyCommit("feat: add endpoint\n\nBREAKING CHANGE: API changed", DefaultGenerateOptions())
	require.Equal(t, breakingChangesSection, section)
	require.Equal(t, "BREAKING CHANGE: API changed", line)

	section, line = classifyCommit("docs: update README", DefaultGenerateOptions())
	require.Equal(t, otherChangesSection, section)
	require.Equal(t, "docs: update README", line)
}

func TestGeneratorGenerateWithCustomSections(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	opts := DefaultGenerateOptions()
	opts.NewContributors = false
	opts.Sections = []SectionRule{
		{Type: "feat", Section: "Highlights"},
		{Type: "fix", Section: "Bugfixes"},
		{Type: "docs", Hidden: true},
	}

	output := generator.Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add search",
			"fix: resolve issue with X",
			"docs: update README",
			"chore: tidy up",
		},
	}, opts)

	require.Equal(t, "<section class=\"changelog-entry\">\n  <h2>v1.3.0 <small>2026-05-25</small></h2>\n  <h3>Highlights</h3>\n  <ul>\n    <li>feat: add search</li>\n  </ul>\n  <h3>Bugfixes</h3>\n  <ul>\n    <li>fix: resolve issue with X</li>\n  </ul>\n  <h3>Other Changes</h3>\n  <ul>\n    <li>chore: tidy up</li>\n  </ul>\n</section>", output)
}

func TestGeneratorGenerateWithCustomSectionsKeepsBreakingChangesFirst(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	opts := DefaultGenerateOptions()
	opts.NewContributors = false
	opts.Sections = []SectionRule{{Type: "feat", Section: "Highlights"}}

	output := generator.Generate(ReleaseContext{
		Version: "2.0.0",
		Commits: []string{
			"feat!: breaking change here",
			"feat: add search",
		},
	}, opts)

	require.Equal(t, "<section class=\"changelog-entry\">\n  <h2>v2.0.0 <small>2026-05-25</small></h2>\n  <h3>Breaking Changes</h3>\n  <ul>\n    <li>feat!: breaking change here</li>\n  </ul>\n  <h3>Highlights</h3>\n  <ul>\n    <li>feat: add search</li>\n  </ul>\n</section>", output)
}

func TestFindSectionRuleIsCaseInsensitive(t *testing.T) {
	t.Parallel()

	rules := []SectionRule{{Type: "Feat", Section: "Features"}}
	rule, ok := findSectionRule(rules, "feat")
	require.True(t, ok)
	require.Equal(t, "Features", rule.Section)

	_, ok = findSectionRule(rules, "fix")
	require.False(t, ok)
}

func TestGeneratorGenerateWithSignature(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	output := generator.Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{"feat: add search"},
	}, GenerateOptions{Signature: true})

	require.Contains(t, output, "<footer><small>Generated by <a href=\"https://semrel.io\">semrel.io</a></small></footer>")
}

func TestGeneratorAIDisclosureBadge(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true

	output := generator.Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
			"fix: plain fix",
		},
	}, opts)

	require.Contains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}

func TestGeneratorAIDisclosureSection(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true
	opts.AIDisclosureSection = true

	output := generator.Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	}, opts)

	require.Contains(t, output, "AI-Assisted Contributions")
	require.Contains(t, output, "Co-authored with <strong>GitHub Copilot</strong>")
	require.Contains(t, output, "L-08 §8")
}

func TestGeneratorAIDisclosureOffByDefault(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	output := generator.Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	})

	require.NotContains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}

func TestGeneratorNewContributors(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	ctx := ReleaseContext{
		Version:       "1.4.0",
		RepositoryURL: "https://github.com/SemRels/generator-changelog-html",
		Commits:       []string{"feat: add login (#42)"},
	}

	t.Run("section rendered when first-time contributors present", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = []Contributor{
			{Name: "Alice", Login: "alice", FirstTime: true, FirstContributionPR: 42},
			{Name: "Bob", Login: "bob", FirstTime: false, CommitCount: 3},
		}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "<h3>New Contributors</h3>")
		require.Contains(t, output, "<a href=\"https://github.com/alice\">@alice</a>")
		require.Contains(t, output, "<a href=\"https://github.com/SemRels/generator-changelog-html/pull/42\">#42</a>")
		require.NotContains(t, output, "@bob")
	})

	t.Run("section skipped when contributors empty", func(t *testing.T) {
		t.Parallel()

		output := generator.Generate(ctx, DefaultGenerateOptions())
		require.NotContains(t, output, "New Contributors")
	})

	t.Run("section skipped when disabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.NewContributors = false
		opts.Contributors = []Contributor{{Name: "Alice", Login: "alice", FirstTime: true}}

		output := generator.Generate(ctx, opts)
		require.NotContains(t, output, "New Contributors")
	})

	t.Run("contributor names are escaped", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = []Contributor{
			{Name: "<script>alert(1)</script>", FirstTime: true, FirstContributionLabel: "#7"},
		}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "&lt;script&gt;alert(1)&lt;/script&gt;")
		require.NotContains(t, output, "<script>alert(1)</script>")
	})
}

func TestGeneratorReleaseMVP(t *testing.T) {
	t.Parallel()

	generator := &Generator{now: func() time.Time {
		return time.Date(2026, 5, 25, 0, 0, 0, 0, time.UTC)
	}}

	ctx := ReleaseContext{
		Version:       "1.4.0",
		RepositoryURL: "https://github.com/SemRels/generator-changelog-html",
		Commits:       []string{"feat: add login (#42)", "fix: patch (#42)", "fix: docs (#99)"},
	}

	t.Run("mvp rendered when enabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.MVP = true
		opts.Contributors = []Contributor{
			{Name: "Alice", Login: "alice", CommitCount: 4},
			{Name: "Bob", Login: "bob", CommitCount: 2},
		}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "<h3>🏆 Release MVP</h3>")
		require.Contains(t, output, "<a href=\"https://github.com/alice\">@alice</a> led the contributors this release.")
	})

	t.Run("mvp skipped when disabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = []Contributor{{Name: "Alice", Login: "alice", CommitCount: 4}}

		output := generator.Generate(ctx, opts)
		require.NotContains(t, output, "Release MVP")
	})

	t.Run("mvp skipped when contributors absent", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.MVP = true

		output := generator.Generate(ctx, opts)
		require.NotContains(t, output, "Release MVP")
	})
}

func TestPickMVPFallsBackToCommitMatching(t *testing.T) {
	t.Parallel()

	mvp := pickMVP([]Contributor{
		{Name: "Alice", Login: "alice", FirstContributionPR: 42},
		{Name: "Bob", Login: "bob", FirstContributionPR: 99},
	}, []string{"feat: add login (#42)", "fix: patch (#42)", "fix: docs (#99)"}, "commits")

	require.NotNil(t, mvp)
	require.Equal(t, "alice", mvp.Login)
}
